### ISSUE TITLE
求一个广东地方台，最好是IPV6的，V4也行，谢谢大佬!

### ISSUE THREAD

**Issue by luoluowoaini** [Meroser/mgtv#4]
求一个广东地方台，最好是IPV6的，V4也行，谢谢大佬!

**Comment by Meroser** [comment]
广东｜珠江,http://php.jdshipin.com:8880/chudian.php?id=gdzj
广东｜民生,http://php.jdshipin.com:8880/chudian.php?id=gdms
广东｜体育,http://php.jdshipin.com:8880/chudian.php?id=gdty
广东｜少儿,http://php.jdshipin.com:8880/chudian.php?id=gdse
广东｜影视,http://php.jdshipin.com:8880/chudian.php?id=gdys
广东｜移动,http://php.jdshipin.com:8880/chudian.php?id=gdyd
广东｜广州新闻,http://php.jdshipin.com:8880/gztv.php?id=xinwen
广东｜广州竞赛,http://php.jdshipin.com:8880/gztv.php?id=jingsai
广东｜广州影视,http://php.jdshipin.com:8880/gztv.php?id=yingshi
广东｜广州法治,http://php.jdshipin.com:8880/gztv.php?id=fazhi

**Comment by luoluowoaini** [comment]
谢谢，这组源我有，体育台一有比赛就放广告的。。。
这个是荔枝的源，但是还是谢谢你




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Meroser/mgtv"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年3月7日(星期四) 晚上7:05
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Meroser/mgtv] 求一个广东地方台，最好是IPV6的，V4也行，谢谢大佬! (Issue #4)





 
广东｜珠江,http://php.jdshipin.com:8880/chudian.php?id=gdzj
 广东｜民生,http://php.jdshipin.com:8880/chudian.php?id=gdms
 广东｜体育,http://php.jdshipin.com:8880/chudian.php?id=gdty
 广东｜少儿,http://php.jdshipin.com:8880/chudian.php?id=gdse
 广东｜影视,http://php.jdshipin.com:8880/chudian.php?id=gdys
 广东｜移动,http://php.jdshipin.com:8880/chudian.php?id=gdyd
 广东｜广州新闻,http://php.jdshipin.com:8880/gztv.php?id=xinwen
 广东｜广州竞赛,http://php.jdshipin.com:8880/gztv.php?id=jingsai
 广东｜广州影视,http://php.jdshipin.com:8880/gztv.php?id=yingshi
 广东｜广州法治,http://php.jdshipin.com:8880/gztv.php?id=fazhi
